# Generated by Django 4.2.23 on 2025-07-28 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pets.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('record_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('vet_notes', models.TextField(blank=True)),
                ('next_visit_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PetDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('VACCINATION', 'Vaccination Record'), ('MEDICAL', 'Medical Report'), ('PRESCRIPTION', 'Prescription'), ('OTHER', 'Other Document')], max_length=20)),
                ('file', models.FileField(upload_to=pets.models.pet_document_path)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.RemoveField(
            model_name='petphoto',
            name='pet',
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='pet',
            name='pets_pet_owner_i_87dd17_idx',
        ),
        migrations.RemoveIndex(
            model_name='pet',
            name='pets_pet_microch_268531_idx',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='microchip_number',
            new_name='color',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='notes',
        ),
        migrations.AddField(
            model_name='pet',
            name='microchip_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='special_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('BIRD', 'Bird'), ('OTHER', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['name'], name='pets_pet_name_7b5b83_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['owner'], name='pets_pet_owner_i_1dbea9_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['species'], name='pets_pet_species_f91a7c_idx'),
        ),
        migrations.DeleteModel(
            name='PetPhoto',
        ),
        migrations.AddField(
            model_name='petdocument',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='pets.pet'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='pets.pet'),
        ),
    ]
