# Generated by Django 5.2.3 on 2025-07-31 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_petphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('BIRD', 'Bird'), ('RABBIT', 'Rabbit'), ('HAMSTER', 'Hamster'), ('GUINEA_PIG', 'Guinea Pig'), ('FISH', 'Fish'), ('TURTLE', 'Turtle'), ('SNAKE', 'Snake'), ('LIZARD', 'Lizard'), ('FERRET', 'Ferret'), ('HORSE', 'Horse'), ('CHICKEN', 'Chicken'), ('PARROT', 'Parrot'), ('OTHER', 'Other')], max_length=10),
        ),
    ]
