# Generated by Django 5.2.3 on 2025-07-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_alter_pet_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='record_type',
            field=models.CharField(choices=[('CHECKUP', 'Regular Checkup'), ('VACCINE', 'Vaccination'), ('TREATMENT', 'Treatment'), ('SURGERY', 'Surgery'), ('TEST', 'Medical Test'), ('INJURY', 'Injury Care'), ('DENTAL', 'Dental Care'), ('EMERGENCY', 'Emergency Visit'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
