# Generated by Django 4.2.23 on 2025-07-31 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0005_alter_medicalrecord_record_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='pet',
            name='age',
            field=models.IntegerField(blank=True, help_text='Age in years', null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL),
        ),
    ]
