# Generated by Django 5.2.3 on 2025-07-31 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_remove_pet_allergies_remove_pet_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='vaccination_status',
            field=models.CharField(choices=[('UP_TO_DATE', 'Up to Date'), ('DUE_SOON', 'Due Soon'), ('OVERDUE', 'Overdue'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', help_text="Current status of pet's vaccinations", max_length=20),
        ),
    ]
