# Generated by Django 4.2.23 on 2025-08-06 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0007_pet_vaccination_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetsMedicalRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('visit_date', models.DateField()),
                ('treatment', models.CharField(max_length=100)),
                ('prescription', models.DateField()),
                ('vaccination_date', models.DateField()),
                ('diagnosis', models.TextField()),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets_medical_records', to='pets.pet')),
                ('vaterian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets_medical_records_vaterian', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
