# Generated by Django 4.2.23 on 2025-08-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petsmedicalrecord',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='medical_files/'),
        ),
    ]
