# Generated by Django 4.2.23 on 2025-08-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_petsmedicalrecord_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petsmedicalrecord',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='records/files/'),
        ),
    ]
