# Generated by Django 4.2.23 on 2025-08-06 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_petsmedicalrecord_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petsmedicalrecord',
            name='file',
        ),
    ]
