# Generated by Django 4.2.23 on 2025-08-20 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0007_pet_vaccination_status'),
        ('records', '0004_remove_petsmedicalrecord_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurgeryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surgery_date', models.DateField()),
                ('surgery_type', models.CharField(max_length=255)),
                ('anesthesia_used', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets_surgery_records', to='pets.pet')),
                ('vaterian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets_surgery_records_vaterian', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Surgery Record',
                'verbose_name_plural': 'Surgery Records',
                'ordering': ['-surgery_date'],
            },
        ),
    ]
