# Generated by Django 4.2.23 on 2025-08-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_surgeryrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgeryrecord',
            name='surgeon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
