# Generated by Django 4.2.23 on 2025-08-20 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_surgeryrecord_surgeon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surgeryrecord',
            old_name='vaterian',
            new_name='veterinarian',
        ),
    ]
