# Generated by Django 4.2.23 on 2025-08-19 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('GENERAL', 'General Checkup'), ('VACCINATION', 'Vaccination'), ('SURGERY', 'Surgery'), ('ILLNESS', 'Illness / Injury'), ('FOLLOWUP', 'Follow-up'), ('OTHER', 'Others')], max_length=20, unique=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='billing',
            name='description',
        ),
        migrations.AlterField(
            model_name='billing',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='service',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='billing.servicecost'),
            preserve_default=False,
        ),
    ]
