# Generated by Django 4.2.23 on 2025-08-01 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appoinments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentreminder',
            name='appointment',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='AppointmentReminder',
        ),
    ]
