# Generated by Django 5.2.3 on 2025-08-04 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='inventoryitem',
            name='inventory_i_quantit_82f142_idx',
        ),
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='low_stock_threshold',
            new_name='minimum_stock_level',
        ),
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='quantity',
            new_name='quantity_in_stock',
        ),
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='cost_price',
            new_name='unit_price',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='supplier_contact',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='supplier_name',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='reorder_point',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['quantity_in_stock'], name='inventory_i_quantit_13ee27_idx'),
        ),
    ]
